apiVersion: batch/v1
kind: Job
metadata:
  name: cuda-matrix-mul
spec:
  template:
    spec:
      containers:
      - name: matrix-mul
        image: bastion:32000/cuda-matrix-mul:latest
        resources:
          limits:
            nvidia.com/gpu: 1 # Requesting 1 GPU
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - cuda1

