apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "python-postgres.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: python-postgres
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "python-postgres.fullname" . }}
              port:
                number: 5000
